export const GET_ALL_COUNTRIES_REQUEST = 'GET_ALL_COUNTRIES_REQUEST';
export const GET_ALL_COUNTRIES_FAIL = 'GET_ALL_COUNTRIES_FAIL';
export const GET_ALL_COUNTRIES_SUCCESS = 'GET_ALL_COUNTRIES_SUCCESS';

export const SEARCH_COUNTRY_REQUEST = 'SEARCH_COUNTRY_REQUEST';
export const SEARCH_COUNTRY_SUCCESS = 'SEARCH_COUNTRY_SUCCESS';
export const SEARCH_COUNTRY_FAIL = 'SEARCH_COUNTRY_FAIL';

export const GET_COUNTRY_REQUEST = 'GET_COUNTRY_REQUEST';
export const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS';
export const GET_COUNTRY_FAIL = 'GET_COUNTRY_FAIL';
